export interface IemployeesData {
  id: number;
  surname: string;
  name: string;
  companyId: number;
  position: string;
}

export const fakeData: IemployeesData[] = [
  {
    id: 1,
    surname: 'Степанов',
    name: 'Андрей',
    companyId: 1,
    position: 'Менеджер',
  },
  {
    id: 2,
    surname: 'Шишкина',
    name: 'Анастасия',
    companyId: 1,
    position: 'Дизайнер',
  },
  {
    id: 3,
    surname: 'Морозов',
    name: 'Глеб',
    companyId: 2,
    position: 'Инженер',
  },
  {
    id: 4,
    surname: 'Иванова',
    name: 'Карина',
    companyId: 2,
    position: 'Программист',
  },
  {
    id: 5,
    surname: 'Васильев',
    name: 'Иван',
    companyId: 3,
    position: 'Директор',
  },
  {
    id: 6,
    surname: 'Озеров',
    name: 'Герман',
    companyId: 3,
    position: 'Охранник',
  },
  {
    id: 7,
    surname: 'Виноградова',
    name: 'Милана',
    companyId: 4,
    position: 'Директор',
  },
  {
    id: 8,
    surname: 'Кудряшова',
    name: 'Дарья',
    companyId: 4,
    position: 'Уборщица',
  },
  {
    id: 9,
    surname: 'Борисова',
    name: 'София',
    companyId: 5,
    position: 'Дизайнер',
  },
  {
    id: 10,
    surname: 'Денисова',
    name: 'Ульяна',
    companyId: 5,
    position: 'Менеджер',
  },
  {
    id: 11,
    surname: 'Степанов',
    name: 'Андрей',
    companyId: 1,
    position: 'Менеджер',
  },
  {
    id: 12,
    surname: 'Степанов',
    name: 'Андрей',
    companyId: 1,
    position: 'Менеджер',
  },
  {
    id: 13,
    surname: 'Степанов',
    name: 'Андрей',
    companyId: 1,
    position: 'Менеджер',
  },
  {
    id: 14,
    surname: 'Степанов',
    name: 'Андрей',
    companyId: 1,
    position: 'Менеджер',
  },
  {
    id: 15,
    surname: 'Степанов',
    name: 'Андрей',
    companyId: 1,
    position: 'Менеджер',
  },
  {
    id: 16,
    surname: 'Степанов',
    name: 'Андрей',
    companyId: 1,
    position: 'Менеджер',
  },
  {
    id: 17,
    surname: 'Степанов',
    name: 'Андрей',
    companyId: 1,
    position: 'Менеджер',
  },
  {
    id: 18,
    surname: 'Степанов',
    name: 'Андрей',
    companyId: 1,
    position: 'Менеджер',
  },
  {
    id: 19,
    surname: 'Степанов',
    name: 'Андрей',
    companyId: 1,
    position: 'Менеджер',
  },
  {
    id: 20,
    surname: 'Степанов',
    name: 'Андрей',
    companyId: 1,
    position: 'Менеджер',
  },
  {
    id: 21,
    surname: 'Степанов',
    name: 'Андрей',
    companyId: 1,
    position: 'Менеджер',
  },
  {
    id: 22,
    surname: 'Степанов',
    name: 'Андрей',
    companyId: 1,
    position: 'Менеджер',
  },
  {
    id: 23,
    surname: 'Степанов',
    name: 'Андрей',
    companyId: 1,
    position: 'Менеджер',
  },
  {
    id: 24,
    surname: 'Степанов',
    name: 'Андрей',
    companyId: 1,
    position: 'Менеджер',
  },
  {
    id: 25,
    surname: 'Степанов',
    name: 'Андрей',
    companyId: 1,
    position: 'Менеджер',
  },
  {
    id: 26,
    surname: 'Степанов',
    name: 'Андрей',
    companyId: 1,
    position: 'Менеджер',
  },
  {
    id: 27,
    surname: 'Степанов',
    name: 'Андрей',
    companyId: 1,
    position: 'Менеджер',
  },
  {
    id: 28,
    surname: 'Степанов',
    name: 'Андрей',
    companyId: 1,
    position: 'Менеджер',
  },
  {
    id: 29,
    surname: 'Степанов',
    name: 'Андрей',
    companyId: 1,
    position: 'Менеджер',
  },
  {
    id: 30,
    surname: 'Степанов',
    name: 'Андрей',
    companyId: 1,
    position: 'Менеджер',
  },
  {
    id: 31,
    surname: 'Степанов',
    name: 'Андрей',
    companyId: 1,
    position: 'Менеджер',
  },
  {
    id: 32,
    surname: 'Степанов',
    name: 'Андрей',
    companyId: 1,
    position: 'Менеджер',
  },
  {
    id: 33,
    surname: 'Степанов',
    name: 'Андрей',
    companyId: 1,
    position: 'Менеджер',
  },
  {
    id: 34,
    surname: 'Степанов',
    name: 'Андрей',
    companyId: 1,
    position: 'Менеджер',
  },
  {
    id: 35,
    surname: 'Степанов',
    name: 'Андрей',
    companyId: 1,
    position: 'Менеджер',
  },
  {
    id: 36,
    surname: 'Степанов',
    name: 'Андрей',
    companyId: 1,
    position: 'Менеджер',
  },
  {
    id: 37,
    surname: 'Степанов',
    name: 'Андрей',
    companyId: 1,
    position: 'Менеджер',
  },
  {
    id: 38,
    surname: 'Степанов',
    name: 'Андрей',
    companyId: 1,
    position: 'Менеджер',
  },
  {
    id: 39,
    surname: 'Степанов',
    name: 'Андрей',
    companyId: 1,
    position: 'Менеджер',
  },
  {
    id: 40,
    surname: 'Степанов',
    name: 'Андрей',
    companyId: 1,
    position: 'Менеджер',
  },
  {
    id: 41,
    surname: 'Степанов',
    name: 'Андрей',
    companyId: 1,
    position: 'Менеджер',
  },
  {
    id: 42,
    surname: 'Степанов',
    name: 'Андрей',
    companyId: 1,
    position: 'Менеджер',
  },
  {
    id: 43,
    surname: 'Степанов',
    name: 'Андрей',
    companyId: 1,
    position: 'Менеджер',
  },
  {
    id: 44,
    surname: 'Степанов',
    name: 'Андрей',
    companyId: 1,
    position: 'Менеджер',
  },
  {
    id: 45,
    surname: 'Степанов',
    name: 'Андрей',
    companyId: 1,
    position: 'Менеджер',
  },
  {
    id: 46,
    surname: 'Степанов',
    name: 'Андрей',
    companyId: 1,
    position: 'Менеджер',
  },
  {
    id: 47,
    surname: 'Степанов',
    name: 'Андрей',
    companyId: 1,
    position: 'Менеджер',
  },
  {
    id: 48,
    surname: 'Степанов',
    name: 'Андрей',
    companyId: 1,
    position: 'Менеджер',
  },
  {
    id: 49,
    surname: 'Степанов',
    name: 'Андрей',
    companyId: 1,
    position: 'Менеджер',
  },
  {
    id: 50,
    surname: 'Степанов',
    name: 'Андрей',
    companyId: 1,
    position: 'Менеджер',
  },
  {
    id: 51,
    surname: 'Степанов',
    name: 'Андрей',
    companyId: 1,
    position: 'Менеджер',
  },
  {
    id: 52,
    surname: 'Степанов',
    name: 'Андрей',
    companyId: 1,
    position: 'Менеджер',
  },
  {
    id: 53,
    surname: 'Степанов',
    name: 'Андрей',
    companyId: 1,
    position: 'Менеджер',
  },
  {
    id: 54,
    surname: 'Степанов',
    name: 'Андрей',
    companyId: 1,
    position: 'Менеджер',
  },
  {
    id: 55,
    surname: 'Степанов',
    name: 'Андрей',
    companyId: 1,
    position: 'Менеджер',
  },
  {
    id: 56,
    surname: 'Степанов',
    name: 'Андрей',
    companyId: 1,
    position: 'Менеджер',
  },
  {
    id: 57,
    surname: 'Степанов',
    name: 'Андрей',
    companyId: 1,
    position: 'Менеджер',
  },
  {
    id: 58,
    surname: 'Степанов',
    name: 'Андрей',
    companyId: 1,
    position: 'Менеджер',
  },
  {
    id: 59,
    surname: 'Степанов',
    name: 'Андрей',
    companyId: 1,
    position: 'Менеджер',
  },
  {
    id: 60,
    surname: 'Степанов',
    name: 'Андрей',
    companyId: 1,
    position: 'Менеджер',
  },
  {
    id: 61,
    surname: 'Степанов',
    name: 'Андрей',
    companyId: 1,
    position: 'Менеджер',
  },
  {
    id: 62,
    surname: 'Степанов',
    name: 'Андрей',
    companyId: 1,
    position: 'Менеджер',
  },
  {
    id: 63,
    surname: 'Степанов',
    name: 'Андрей',
    companyId: 1,
    position: 'Менеджер',
  },
  {
    id: 64,
    surname: 'Степанов',
    name: 'Андрей',
    companyId: 1,
    position: 'Менеджер',
  },
  {
    id: 65,
    surname: 'Степанов',
    name: 'Андрей',
    companyId: 1,
    position: 'Менеджер',
  },
  {
    id: 66,
    surname: 'Степанов',
    name: 'Андрей',
    companyId: 1,
    position: 'Менеджер',
  },
  {
    id: 67,
    surname: 'Степанов',
    name: 'Андрей',
    companyId: 1,
    position: 'Менеджер',
  },
  {
    id: 68,
    surname: 'Степанов',
    name: 'Андрей',
    companyId: 1,
    position: 'Менеджер',
  },
  {
    id: 69,
    surname: 'Степанов',
    name: 'Андрей',
    companyId: 1,
    position: 'Менеджер',
  },
  {
    id: 70,
    surname: 'Степанов',
    name: 'Андрей',
    companyId: 1,
    position: 'Менеджер',
  },
  {
    id: 71,
    surname: 'Степанов',
    name: 'Андрей',
    companyId: 1,
    position: 'Менеджер',
  },
  {
    id: 72,
    surname: 'Степанов',
    name: 'Андрей',
    companyId: 1,
    position: 'Менеджер',
  },
  {
    id: 73,
    surname: 'Степанов',
    name: 'Андрей',
    companyId: 1,
    position: 'Менеджер',
  },
  {
    id: 74,
    surname: 'Степанов',
    name: 'Андрей',
    companyId: 1,
    position: 'Менеджер',
  },
  {
    id: 75,
    surname: 'Степанов',
    name: 'Андрей',
    companyId: 1,
    position: 'Менеджер',
  },
  {
    id: 76,
    surname: 'Степанов',
    name: 'Андрей',
    companyId: 1,
    position: 'Менеджер',
  },
  {
    id: 77,
    surname: 'Степанов',
    name: 'Андрей',
    companyId: 1,
    position: 'Менеджер',
  },
  {
    id: 78,
    surname: 'Степанов',
    name: 'Андрей',
    companyId: 1,
    position: 'Менеджер',
  },
  {
    id: 79,
    surname: 'Степанов',
    name: 'Андрей',
    companyId: 1,
    position: 'Менеджер',
  },
  {
    id: 80,
    surname: 'Степанов',
    name: 'Андрей',
    companyId: 1,
    position: 'Менеджер',
  },
  {
    id: 81,
    surname: 'Степанов',
    name: 'Андрей',
    companyId: 1,
    position: 'Менеджер',
  },
  {
    id: 82,
    surname: 'Степанов',
    name: 'Андрей',
    companyId: 1,
    position: 'Менеджер',
  },
  {
    id: 83,
    surname: 'Степанов',
    name: 'Андрей',
    companyId: 1,
    position: 'Менеджер',
  },
  {
    id: 84,
    surname: 'Степанов',
    name: 'Андрей',
    companyId: 1,
    position: 'Менеджер',
  },
  {
    id: 85,
    surname: 'Степанов',
    name: 'Андрей',
    companyId: 1,
    position: 'Менеджер',
  },
  {
    id: 86,
    surname: 'Степанов',
    name: 'Андрей',
    companyId: 1,
    position: 'Менеджер',
  },
  {
    id: 87,
    surname: 'Степанов',
    name: 'Андрей',
    companyId: 1,
    position: 'Менеджер',
  },
  {
    id: 88,
    surname: 'Степанов',
    name: 'Андрей',
    companyId: 1,
    position: 'Менеджер',
  },
  {
    id: 89,
    surname: 'Степанов',
    name: 'Андрей',
    companyId: 1,
    position: 'Менеджер',
  },
  {
    id: 90,
    surname: 'Степанов',
    name: 'Андрей',
    companyId: 1,
    position: 'Менеджер',
  },
  {
    id: 91,
    surname: 'Степанов',
    name: 'Андрей',
    companyId: 1,
    position: 'Менеджер',
  },
  {
    id: 92,
    surname: 'Степанов',
    name: 'Андрей',
    companyId: 1,
    position: 'Менеджер',
  },
  {
    id: 93,
    surname: 'Степанов',
    name: 'Андрей',
    companyId: 1,
    position: 'Менеджер',
  },
  {
    id: 94,
    surname: 'Степанов',
    name: 'Андрей',
    companyId: 1,
    position: 'Менеджер',
  },
  {
    id: 95,
    surname: 'Степанов',
    name: 'Андрей',
    companyId: 1,
    position: 'Менеджер',
  },
  {
    id: 96,
    surname: 'Степанов',
    name: 'Андрей',
    companyId: 1,
    position: 'Менеджер',
  },
  {
    id: 97,
    surname: 'Степанов',
    name: 'Андрей',
    companyId: 1,
    position: 'Менеджер',
  },
  {
    id: 98,
    surname: 'Степанов',
    name: 'Андрей',
    companyId: 1,
    position: 'Менеджер',
  },
  {
    id: 99,
    surname: 'Степанов',
    name: 'Андрей',
    companyId: 1,
    position: 'Менеджер',
  },
  {
    id: 100,
    surname: 'Степанов',
    name: 'Андрей',
    companyId: 1,
    position: 'Менеджер',
  },
  {
    id: 101,
    surname: 'Степанов',
    name: 'Андрей',
    companyId: 1,
    position: 'Менеджер',
  },
  {
    id: 102,
    surname: 'Степанов',
    name: 'Андрей',
    companyId: 1,
    position: 'Менеджер',
  },
  {
    id: 103,
    surname: 'Степанов',
    name: 'Андрей',
    companyId: 1,
    position: 'Менеджер',
  },
  {
    id: 104,
    surname: 'Степанов',
    name: 'Андрей',
    companyId: 1,
    position: 'Менеджер',
  },
  {
    id: 105,
    surname: 'Степанов',
    name: 'Андрей',
    companyId: 1,
    position: 'Менеджер',
  },
  {
    id: 106,
    surname: 'Степанов',
    name: 'Андрей',
    companyId: 1,
    position: 'Менеджер',
  },
  {
    id: 107,
    surname: 'Степанов',
    name: 'Андрей',
    companyId: 1,
    position: 'Менеджер',
  },
  {
    id: 108,
    surname: 'Степанов',
    name: 'Андрей',
    companyId: 1,
    position: 'Менеджер',
  },
  {
    id: 109,
    surname: 'Степанов',
    name: 'Андрей',
    companyId: 1,
    position: 'Менеджер',
  },
  {
    id: 110,
    surname: 'Степанов',
    name: 'Андрей',
    companyId: 1,
    position: 'Менеджер',
  },
  {
    id: 111,
    surname: 'Степанов',
    name: 'Андрей',
    companyId: 1,
    position: 'Менеджер',
  },
  {
    id: 112,
    surname: 'Степанов',
    name: 'Андрей',
    companyId: 1,
    position: 'Менеджер',
  },
  {
    id: 113,
    surname: 'Степанов',
    name: 'Андрей',
    companyId: 1,
    position: 'Менеджер',
  },
  {
    id: 114,
    surname: 'Степанов',
    name: 'Андрей',
    companyId: 1,
    position: 'Менеджер',
  },
  {
    id: 115,
    surname: 'Степанов',
    name: 'Андрей',
    companyId: 1,
    position: 'Менеджер',
  },
  {
    id: 116,
    surname: 'Степанов',
    name: 'Андрей',
    companyId: 1,
    position: 'Менеджер',
  },
  {
    id: 117,
    surname: 'Степанов',
    name: 'Андрей',
    companyId: 1,
    position: 'Менеджер',
  },
  {
    id: 118,
    surname: 'Степанов',
    name: 'Андрей',
    companyId: 1,
    position: 'Менеджер',
  },
  {
    id: 119,
    surname: 'Степанов',
    name: 'Андрей',
    companyId: 1,
    position: 'Менеджер',
  },
  {
    id: 120,
    surname: 'Степанов',
    name: 'Андрей',
    companyId: 1,
    position: 'Менеджер',
  },
];
